import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';

import './globals.css';
import { auth } from '@/auth';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
	const session = await auth();

	return (
		<html lang='en'>
			<body className={inter.className}>
				<SessionProvider session={session}>
					<Toaster />
					{children}
				</SessionProvider>
			</body>
		</html>
	);
};

export default RootLayout;
